[package]
name = "enforce"
version = "0.1.0"
authors = ["Brett Mayson <brett@vivvo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "*"
pest_derive = "*"
clap = "*"
lazy_static = "*"
